version: '3'
services:
  node:
    image: node:18.16-alpine
    working_dir: /app
    environment:
      - NODE_ENV=${NEXT_PUBLIC_REACT_ENV}
    volumes:
      - ./:/app
    ports:
      - "${PORT}:3000"
    command: [ "npm", "run", "dev" ]
