
name: Build and deploy to production 

on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decrypt large secret
        run: ./.github/decrypt_secret.sh
        env: 
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/key

      - name: Log in to the Container registry
        # uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: putting the enviroment for container
        run: | 
          echo "NEXT_PUBLIC_PRODUCTION_API_URL=${{ vars.NEXT_PUBLIC_PRODUCTION_API_URL }}" >> .env.production
          echo "NEXT_PUBLIC_PRODUCTION_DOMAIN_URL=${{ vars.NEXT_PUBLIC_PRODUCTION_DOMAIN_URL }}" >> .env.production
          echo "NEXT_PUBLIC_REACT_ENV=${{ vars.NEXT_PUBLIC_REACT_ENV }}" >> .env.production

      - name: echo the .env.production file
        run: cat .env.production

      - name: build image 
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f ./docker/production.dockerfile .

      - name: push to registry 
        run: docker push ${{ env.REGISTRY }}/$IMAGE_NAME:latest
    