
name: Build and deploy to production 

on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decrypt large secret
        run: ./.github/decrypt_secret.sh
        env: 
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

      - name: Log in to the Container registry

        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: putting the enviroment for container
        run: | 
          echo "NEXT_PUBLIC_PRODUCTION_API_URL=${{ vars.NEXT_PUBLIC_PRODUCTION_API_URL }}" >> .env.production
          echo "NEXT_PUBLIC_PRODUCTION_DOMAIN_URL=${{ vars.NEXT_PUBLIC_PRODUCTION_DOMAIN_URL }}" >> .env.production
          echo "NEXT_PUBLIC_REACT_ENV=${{ vars.NEXT_PUBLIC_REACT_ENV }}" >> .env.production

      - name: build image 
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f ./docker/production.dockerfile .

      - name: push to registry 
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to production
        run: | 
        chmod og= $HOME/secrets/key
        ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}"
        ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ vars.SERVER_PATH }} && docker-compose pull && docker-compose up -d --force-recreate"


    