
name: Build and deploy to production 

on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        # uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build image 
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f ./docker/production.dockerfile .

      - name: push to registry 
        run: docker push ${{ env.REGISTRY }}/$IMAGE_NAME:latest
      
      
      # - name: build the docker image 
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./docker/production.dockerfile
      #     push: true
      #     tags: frontent:latest