
name: Build and deploy to production 

on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: putting the enviroment for container
        run: | 
          echo "NEXT_PUBLIC_PRODUCTION_API_URL=${{ vars.NEXT_PUBLIC_PRODUCTION_API_URL }}" >> .env.production
          echo "NEXT_PUBLIC_PRODUCTION_DOMAIN_URL=${{ vars.NEXT_PUBLIC_PRODUCTION_DOMAIN_URL }}" >> .env.production
          echo "NEXT_PUBLIC_REACT_ENV=${{ vars.NEXT_PUBLIC_REACT_ENV }}" >> .env.production

      - name: build image 
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f ./docker/production.dockerfile .

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push to registry 
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest   

  deploy-image:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
      - name: Deploy to production
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
            cd ${{ vars.SERVER_PATH }}
            docker compose pull && docker compose up -d --force-recreate
          host: ${{ vars.SERVER_IP }}
          user: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SECRET_KEY }}   
    